name = "mamboxritalin"
author = "A8gust"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0886a4616d9a101ac4ff90a690599b5b7adc806959c51274142cf89f29a09f6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
