name = "mamboxritalin"
author = "A8gust"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d437496f773d6447433129e2f306c3efd0c07d54b7a550a57a144bf2e67f221"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
