name = "mamboxritalin"
author = "A8gust"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8676f91c00adbbc4841edb5fab5a98bb24b44eda6b65e121f7c2ce2710e31beb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
